### ISSUE TITLE
Adding  TemperatureCalibrator to hardware causes strange behavior

### ISSUE THREAD

**Issue by imaitland** [ssec-jhu/evolver-ng#212] opened 2024-11-20 22:01 UTC
When adding a calibrator to hardware, the affected hardware's config gets messed up.

interestingly this doesn't happen on the actual device in Arik's office. Just evolver-ng (commit: b2fb438e9557a1b87e6a7146f89fbc39db6e4cb6) running on my laptop.

@amitschang says:

here is a scripty way to reproduce:
```
from evolver.device import Evolver
from evolver.hardware.standard.temperature import Temperature
from evolver.calibration.standard.calibrators.temperature import TemperatureCalibrator

#calibrator=None
calibrator = TemperatureCalibrator()
x = Evolver(hardware={'test': Temperature(addr='x', calibrator=calibrator)}).config_model
print(x)
```
one thing I noticed going through is that in the model_validate code, it is not actually a BaseInterface, it is a dict object so hits the very last line, and one notable (maybe) thing is that the nested calibrator object is not json of the config, but rather the object, seems maybe suspect(??)
```
{'evolver': None, 'name': 'Temperature', 'logger': <Logger Temperature (WARNING)>, 'calibrator': <evolver.calibration...1061de150>, 'vials': [0, 1, 2, 3, 4, 5, 6, 7, 8, ...], 'addr': 'x', 'slots': 16, 'serial_conn': None, 'proposal': {}, 'committed': {}, 'outputs': {}}
```

**Comment by jamienoss** [comment] 2024-11-21 19:20
Duplicate of #213

**Closed by jamienoss** 2024-11-21 19:20 UTC
